# Generated by Django 2.2.7 on 2019-11-27 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movieName', models.CharField(max_length=150)),
                ('movieNameEn', models.CharField(max_length=150)),
                ('watchGrade', models.CharField(max_length=150)),
                ('openDate', models.DateField()),
                ('runningTime', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=45)),
                ('summary', models.TextField()),
                ('posterUrl', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=100)),
                ('bechdelRating', models.IntegerField()),
                ('naverRating', models.FloatField()),
                ('genre', models.ManyToManyField(related_name='movie_genres', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_movies', to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
